docs/tools/overview.md
Closes #24 
Adds link to Vega Tools repo to the tools overview page
=> Add Vega Tools to overview

docs/api/overview.md, docs/api/rest/overview.md, docs/concepts/vega-chain.md, docs/graphql/generated.md, docusaurus.config.js, package.json, yarn.lock
This PR adds the GQL playground link, reorganises the testnet api info into an admonition and adds more info about automatic nominations
=> Add and update some links

docs/concepts/vega-chain.md
Rewards are proportional to the amount of stake, and this PR makes that clear in the concepts.
=> Update how rewards are divided up

docs/tools/vega-wallet/cli-wallet/latest/guides/manage-networks.md
Closes https://github.com/vegaprotocol/vegawallet-desktop/issues/54
=> Add section to manage network page that highlights URLs

docs/tools/index.md, docs/tools/vega-wallet/cli-wallet/_category_.json, docs/tools/vega-wallet/cli-wallet/index.md, docs/tools/vega-wallet/cli-wallet/latest/create-wallet.md, docs/tools/vega-wallet/desktop-app/_category_.json, docs/tools/vega-wallet/desktop-app/index.md, docs/tools/vega-wallet/desktop-app/latest/_category_.json, docs/tools/vega-wallet/desktop-app/latest/getting-started.md, docs/tools/vega-wallet/desktop-wallet/index.md, docs/tools/vega-wallet/index.md
=> Create section for desktop wallet

docs/concepts/vega-chain.md, docs/tools/vega-wallet/desktop-app/latest/getting-started.md
- Make explicit that staking rewards need to be withdrawn before they can be staked 
- Add instructions for updating the desktop wallet app
=> Rewards & Updating desktop wallet

src/components/HomepageFeatures.js
=> Fixes tools link on homepage

docs/concepts/new-to-vega.md, docs/tools/vega-wallet/desktop-app/latest/getting-started.md
This PR replaces the links provided for users to share feedback.
=> Replace nolt with gh discussions links

docs/releases/core/release-notes.md, docs/releases/data-node/release-notes.md
=> Add notes for 0.50 ahead of release

docs/tools/index.md
Adds Capsule & block explorer to the apps & tools page and links off to their respective homes.
=> Add capsule section to tools page

docs/releases/overview.md, docs/tools/vega-wallet/cli-wallet/latest/guides/manage-networks.md, versioned_docs/version-v0.47.0/tools/vega-wallet/cli-wallet/latest/guides/manage-networks.md, versioned_docs/version-v0.50.2/releases/overview.md, versioned_docs/version-v0.50.2/tools/vega-wallet/cli-wallet/latest/guides/manage-networks.md
This PR adds some formatting improvements to the releases page & incorporates improvements to the networks guide for wallet based on feedback.
=> Releases & manage network pages - quality of life improvements

docs/tutorials/index.md, docs/tutorials/proposals/new-market-proposal.md, docs/tutorials/using-oracle-data.md
Reword the page based on changes to the [data sourcing spec](https://github.com/vegaprotocol/specs/pull/1161).
=> Rename file & reword sections of oracle data tutorial

versioned_sidebars/version-v0.50.2-sidebars.json
Fix an incorrect ref in the versioned sidebar
=> Fix 0.50.x graphql sidebar. Closes #167

docs/concepts/vega-protocol.md, docs/tutorials/proposals/network-parameter-proposal.md, docs/tutorials/proposals/new-market-proposal.md, docs/tutorials/proposals/update-market-proposal.md
Minor shuffle of some content related to Network Paramater configuration
- Remove near-duplicate reference to tokens in New Market Proposal tutorial intro
- Add Network Parameter component to Vega Concepts page
=> Improvements to proposal content

docs/tutorials/proposals/_generated-proposals/_newAsset_annotated.md, docs/tutorials/proposals/_generated-proposals/_newAsset_cmd.md, docs/tutorials/proposals/_generated-proposals/_newAsset_json.md, docs/tutorials/proposals/_generated-proposals/_newAsset_win.md, docs/tutorials/proposals/_generated-proposals/_newFreeform_annotated.md, docs/tutorials/proposals/_generated-proposals/_newFreeform_cmd.md, docs/tutorials/proposals/_generated-proposals/_newFreeform_json.md, docs/tutorials/proposals/_generated-proposals/_newFreeform_win.md, docs/tutorials/proposals/_generated-proposals/_newMarket_annotated.md, docs/tutorials/proposals/_generated-proposals/_newMarket_cmd.md, docs/tutorials/proposals/_generated-proposals/_newMarket_json.md, docs/tutorials/proposals/_generated-proposals/_newMarket_json_instrument.md, docs/tutorials/proposals/_generated-proposals/_newMarket_json_overview.md, docs/tutorials/proposals/_generated-proposals/_newMarket_win.md, docs/tutorials/proposals/_generated-proposals/_updateMarket_annotated.md, docs/tutorials/proposals/_generated-proposals/_updateMarket_cmd.md, docs/tutorials/proposals/_generated-proposals/_updateMarket_json.md, docs/tutorials/proposals/_generated-proposals/_updateMarket_win.md, docs/tutorials/proposals/_generated-proposals/_updateNetworkParameter_annotated.md, docs/tutorials/proposals/_generated-proposals/_updateNetworkParameter_cmd.md, docs/tutorials/proposals/_generated-proposals/_updateNetworkParameter_json.md, docs/tutorials/proposals/_generated-proposals/_updateNetworkParameter_win.md, scripts/generate_proposals.js, scripts/libGenerateProposals/newMarket.js
The asset this market is using is 5 decimal places, while the example uses 18. 
- Fix generated newMarket sample to use 5 decimal places
=> Fix new market example

docs/api/vega-wallet/index.md
this PR removes an unneeded space and tests out some new functionality
=> remove space

docs/tutorials/proposals/_generated-proposals/_newAsset_annotated.md, docs/tutorials/proposals/_generated-proposals/_newAsset_cmd.md, docs/tutorials/proposals/_generated-proposals/_newAsset_json.md, docs/tutorials/proposals/_generated-proposals/_newAsset_win.md, docs/tutorials/proposals/_generated-proposals/_newFreeform_annotated.md, docs/tutorials/proposals/_generated-proposals/_newFreeform_cmd.md, docs/tutorials/proposals/_generated-proposals/_newFreeform_json.md, docs/tutorials/proposals/_generated-proposals/_newFreeform_win.md, docs/tutorials/proposals/_generated-proposals/_newMarket_annotated.md, docs/tutorials/proposals/_generated-proposals/_newMarket_cmd.md, docs/tutorials/proposals/_generated-proposals/_newMarket_json.md, docs/tutorials/proposals/_generated-proposals/_newMarket_json_instrument.md, docs/tutorials/proposals/_generated-proposals/_newMarket_json_overview.md, docs/tutorials/proposals/_generated-proposals/_newMarket_win.md, docs/tutorials/proposals/_generated-proposals/_updateAsset_annotated.md, docs/tutorials/proposals/_generated-proposals/_updateAsset_cmd.md, docs/tutorials/proposals/_generated-proposals/_updateAsset_json.md, docs/tutorials/proposals/_generated-proposals/_updateAsset_win.md, docs/tutorials/proposals/_generated-proposals/_updateMarket_annotated.md, docs/tutorials/proposals/_generated-proposals/_updateMarket_cmd.md, docs/tutorials/proposals/_generated-proposals/_updateMarket_json.md, docs/tutorials/proposals/_generated-proposals/_updateMarket_win.md, docs/tutorials/proposals/_generated-proposals/_updateNetworkParameter_annotated.md, docs/tutorials/proposals/_generated-proposals/_updateNetworkParameter_cmd.md, docs/tutorials/proposals/_generated-proposals/_updateNetworkParameter_json.md, docs/tutorials/proposals/_generated-proposals/_updateNetworkParameter_win.md, scripts/libGenerateProposals/newMarket.js, scripts/libGenerateProposals/updateMarket.js
Adds metadata to the updateMarket generated sample
- Add metadata property
Closes #270
=> Add metadata to updateMarket

docs/concepts/accounts.md, docs/concepts/trading-on-vega/settlement.md
This PR adds the settlement concept page that was reviewed in another [PR](#113).
=> Add settlement concept page 

docs/releases/overview.md
Add the release notes to support the 0.56 core release to testnet
=> 0.56 release summary

docs/tutorials/transferring-assets.md
Two fields changes:
- dispatchMetric -> metric
- marketsInScope -> markets
Closes #306
=> Update transfer examples for v0.57.0

docs/tutorials/proposals/_generated-proposals/_newAsset_annotated.md, docs/tutorials/proposals/_generated-proposals/_newAsset_cmd.md, docs/tutorials/proposals/_generated-proposals/_newAsset_json.md, docs/tutorials/proposals/_generated-proposals/_newAsset_win.md, docs/tutorials/proposals/_generated-proposals/_newFreeform_annotated.md, docs/tutorials/proposals/_generated-proposals/_newFreeform_cmd.md, docs/tutorials/proposals/_generated-proposals/_newFreeform_json.md, docs/tutorials/proposals/_generated-proposals/_newFreeform_win.md, docs/tutorials/proposals/_generated-proposals/_newMarket_annotated.md, docs/tutorials/proposals/_generated-proposals/_newMarket_cmd.md, docs/tutorials/proposals/_generated-proposals/_newMarket_json.md, docs/tutorials/proposals/_generated-proposals/_newMarket_json_overview.md, docs/tutorials/proposals/_generated-proposals/_newMarket_win.md, docs/tutorials/proposals/_generated-proposals/_updateAsset_annotated.md, docs/tutorials/proposals/_generated-proposals/_updateAsset_cmd.md, docs/tutorials/proposals/_generated-proposals/_updateAsset_json.md, docs/tutorials/proposals/_generated-proposals/_updateAsset_win.md, docs/tutorials/proposals/_generated-proposals/_updateMarket_annotated.md, docs/tutorials/proposals/_generated-proposals/_updateMarket_cmd.md, docs/tutorials/proposals/_generated-proposals/_updateMarket_json.md, docs/tutorials/proposals/_generated-proposals/_updateMarket_win.md, docs/tutorials/proposals/_generated-proposals/_updateNetworkParameter_annotated.md, docs/tutorials/proposals/_generated-proposals/_updateNetworkParameter_cmd.md, docs/tutorials/proposals/_generated-proposals/_updateNetworkParameter_json.md, docs/tutorials/proposals/_generated-proposals/_updateNetworkParameter_win.md, scripts/libGenerateProposals/newAsset.js
Proposal samples use outdated ERC20 addresses on testnet, and thus fail
- Fix erc20 addresses to be correct for sepolia
- Update proposals
Closes #334
=> Fix new asset proposals

vercel.json
=> Silence vercel deploy comments while trialing vercel alongside netlify

docs/releases/overview.md
Draft PR for your visibility @candida-d
=> feat: Add 0.58 release summary notes

docs/releases/overview.md
close #342 .
Not to be merged until 0.59.0 is on testnet
=> feat: add 0.59.0 release note summary

docs/api/grpc/overview.md, docs/api/overview.md, docs/concepts/new-to-vega.md, docs/concepts/trading-on-vega/fees-rewards.md, docs/concepts/trading-on-vega/index.md, docs/concepts/trading-on-vega/market-protections.md, docs/concepts/trading-on-vega/settlement.md, docs/concepts/trading-on-vega/trading-modes.md, docs/concepts/vega-chain.md, docs/concepts/vega-protocol.md, docs/tools/index.md, docs/tools/vega-wallet/cli-wallet/latest/create-wallet.md, docs/tutorials/proposals/freeform-proposal.md, docs/tutorials/proposals/network-parameter-proposal.md, docs/tutorials/proposals/new-asset-proposal.md, docs/tutorials/proposals/new-market-proposal.md, docs/tutorials/proposals/update-asset-proposal.md, docs/tutorials/proposals/update-market-proposal.md, sidebars.js, src/pages/index.js, versioned_docs/version-v0.53/concepts/vega-protocol.md, versioned_docs/version-v0.53/tools/vega-wallet/cli-wallet/latest/create-wallet.md
This PR:
- Closes #339 -  "Vega supports cash settled futures"
- Closes #335 -  Governance Proposals: link to UI 
- Closes #230 - Make it clear what timestamp the minEnactment network params reference
- Closes #136 - more info for adding networks via file
- Closes #127 - Make (Core/CoreState/TradingData)Service More Visible
- Closes #115 - Add tools links for deployed sites
=> Ticket-closing bonanza

docs/concepts/trading-on-vega/positions-margin.md, docs/tutorials/proposals/_generated-proposals/_newAsset_annotated.md, docs/tutorials/proposals/_generated-proposals/_newAsset_cmd.md, docs/tutorials/proposals/_generated-proposals/_newAsset_json.md, docs/tutorials/proposals/_generated-proposals/_newAsset_win.md, docs/tutorials/proposals/_generated-proposals/_newFreeform_annotated.md, docs/tutorials/proposals/_generated-proposals/_newFreeform_cmd.md, docs/tutorials/proposals/_generated-proposals/_newFreeform_json.md, docs/tutorials/proposals/_generated-proposals/_newFreeform_win.md, docs/tutorials/proposals/_generated-proposals/_newMarket_annotated.md, docs/tutorials/proposals/_generated-proposals/_newMarket_cmd.md, docs/tutorials/proposals/_generated-proposals/_newMarket_json.md, docs/tutorials/proposals/_generated-proposals/_newMarket_json_overview.md, docs/tutorials/proposals/_generated-proposals/_newMarket_json_risk.md, docs/tutorials/proposals/_generated-proposals/_newMarket_win.md, docs/tutorials/proposals/_generated-proposals/_updateAsset_annotated.md, docs/tutorials/proposals/_generated-proposals/_updateAsset_cmd.md, docs/tutorials/proposals/_generated-proposals/_updateAsset_json.md, docs/tutorials/proposals/_generated-proposals/_updateAsset_win.md, docs/tutorials/proposals/_generated-proposals/_updateMarket_annotated.md, docs/tutorials/proposals/_generated-proposals/_updateMarket_cmd.md, docs/tutorials/proposals/_generated-proposals/_updateMarket_json.md, docs/tutorials/proposals/_generated-proposals/_updateMarket_win.md, docs/tutorials/proposals/_generated-proposals/_updateNetworkParameter_annotated.md, docs/tutorials/proposals/_generated-proposals/_updateNetworkParameter_cmd.md, docs/tutorials/proposals/_generated-proposals/_updateNetworkParameter_json.md, docs/tutorials/proposals/_generated-proposals/_updateNetworkParameter_win.md, docs/tutorials/proposals/new-market-proposal.md, scripts/generate_proposals.js
... and tidy up the margin examples formatting in the concepts page.
=> Add risk model section to market proposal tutorial

docs/api/vega-wallet/index.md, docs/api/vega-wallet/v2-api/get-started.md
JSON RPC urls and prefixes were wrong
=> Fix JSON RPC URLs

docs/api/overview.md, docs/api/vega-wallet/index.md, docs/api/vega-wallet/v2-api/get-started.md, docs/concepts/vega-wallet.md, docs/tools/vega-wallet/cli-wallet/latest/create-wallet.md, docs/tools/vega-wallet/cli-wallet/latest/guides/restore-wallet.md, docs/tools/vega-wallet/desktop-app/latest/getting-started.md, versioned_docs/version-v0.53/node-operators/snapshots.md, versioned_docs/version-v0.53/tools/vega-wallet/cli-wallet/latest/guides/restore-wallet.md, versioned_docs/version-v0.53/tools/vega-wallet/desktop-app/latest/getting-started.md
=> Revamp 'getting started' for wallet api changes

docs/concepts/accounts.md, docs/concepts/deposits-withdrawals.md, docs/concepts/trading-on-vega/positions-margin.md, docs/concepts/trading-on-vega/settlement.md
=> Link netparams on margin page

versioned_docs/version-v0.53/node-operators/setup-validator.md
=> Add ethereum archive node note to setup guide

VERSIONING.md
The versioning guide was outdated
- Rewrite `VERSIONING.md`
CLoses #380
=> Overhaul versioning doc

docs/tutorials/proposals/_generated-proposals/_newAsset_annotated.md, docs/tutorials/proposals/_generated-proposals/_newAsset_cmd.md, docs/tutorials/proposals/_generated-proposals/_newAsset_json.md, docs/tutorials/proposals/_generated-proposals/_newAsset_win.md, docs/tutorials/proposals/_generated-proposals/_newFreeform_annotated.md, docs/tutorials/proposals/_generated-proposals/_newFreeform_cmd.md, docs/tutorials/proposals/_generated-proposals/_newFreeform_json.md, docs/tutorials/proposals/_generated-proposals/_newFreeform_win.md, docs/tutorials/proposals/_generated-proposals/_newMarket_annotated.md, docs/tutorials/proposals/_generated-proposals/_newMarket_cmd.md, docs/tutorials/proposals/_generated-proposals/_newMarket_json.md, docs/tutorials/proposals/_generated-proposals/_newMarket_json_instrument.md, docs/tutorials/proposals/_generated-proposals/_newMarket_json_overview.md, docs/tutorials/proposals/_generated-proposals/_newMarket_win.md, docs/tutorials/proposals/_generated-proposals/_updateAsset_annotated.md, docs/tutorials/proposals/_generated-proposals/_updateAsset_cmd.md, docs/tutorials/proposals/_generated-proposals/_updateAsset_json.md, docs/tutorials/proposals/_generated-proposals/_updateAsset_win.md, docs/tutorials/proposals/_generated-proposals/_updateMarket_annotated.md, docs/tutorials/proposals/_generated-proposals/_updateMarket_cmd.md, docs/tutorials/proposals/_generated-proposals/_updateMarket_json.md, docs/tutorials/proposals/_generated-proposals/_updateMarket_win.md, docs/tutorials/proposals/_generated-proposals/_updateNetworkParameter_annotated.md, docs/tutorials/proposals/_generated-proposals/_updateNetworkParameter_cmd.md, docs/tutorials/proposals/_generated-proposals/_updateNetworkParameter_json.md, docs/tutorials/proposals/_generated-proposals/_updateNetworkParameter_win.md, scripts/libGenerateProposals/newMarket.js
The script was broken in #435. Command line examples were fine
but the annotated version showed incorrect data.
- Fix newMarket annotated version generation
- Update all generated proposals.
Closes #439
=> Fix incorrect generation of annotated new market proposal

docs/tutorials/committing-liquidity.md
=> Replace LP tutorial links/refs

versioned_docs/version-v0.53/tools/vega-wallet/desktop-app/latest/getting-started.md
=> Add section on managing networks to DW - mainnet

docs/node-operators/get-started/setup-datanode.md
=> Data node setup: Add history retention flags & fetch info

docs/node-operators/get-started/setup-validator.md, docs/node-operators/how-to/rotate-ethereum-keys.md, versioned_docs/version-v0.53/node-operators/setup-validator.md
=> Update clef external link

docs/node-operators/how-to/restart-network.md, docs/node-operators/migration-guides/index.md
* Update restart using checkpoints guide to remove old requirements 
* Add step-by-step guidance to the migration guide for 0.67
=> Restart network & migration guide updates

docs/api/vega-wallet/v2-api/get-started.md, docs/api/vega-wallet/v2-api/integrate-wallet-service.md, docs/api/vega-wallet/v2-api/openrpc.md
Closes #417 
Open question: 
Is the wallet api V2 section the best place for this guide?
=> Add the integrate wallet guide

docs/concepts/vega-chain/transactions.md, docs/concepts/vega-chain/validator-nodes.md, docs/concepts/vega-chain/validator-scores-and-rewards.md
Describe transactions and features related to them.
=> Add transactions concepts

docs/concepts/liquidity/rewards-penalties.md, docs/concepts/trading-on-vega/market-protections.md, docs/tutorials/transferring-assets.md
=> Ref reward pools on LP reward page & tutorials

docs/concepts/vega-chain/network.md, docs/node-operators/get-started/setup-validator.md
To merge when 0.68 is on testnet
=> Remove payload settings line & incl. wallet enhancement for spam/pow

docs/node-operators/how-to/solve-frequent-issues.md
Closes #501. This page introduces a problem/solution list of issues seen internally (and potentially by actual node operators) when running a validator or data node.
=> Page for common issues for node operators

docs/concepts/liquidity/provision.md, docs/concepts/trading-on-vega/fees-rewards.md, docs/concepts/trading-on-vega/orders.md
Adds information about post-only limit order option and reduce-only option, and references conditionals in other places where they seem relevant.
=> Post & reduce only conditionals [v.0.70]

docs/concepts/vega-chain/data-nodes.md, docs/node-operators/get-started/setup-datanode.md
Adding information regarding overriding chunk intervals for Timescale tables in data node.
=> chore: add information about configuring chunk intervals  [v.0.70]

docs/node-operators/get-started/setup-datanode.md
Update the datanode docs to remove the wipe flag and document the unsafe_reset_all command
=> feat: update datanode docs with reset command [0.71.0]

docs/node-operators/how-to/use-snapshots.md, versioned_docs/version-v0.71/node-operators/how-to/use-snapshots.md
=> chore: update snapshot documentation

docs/concepts/assets/deposits-withdrawals.md, docs/tutorials/proposals/new-asset-proposal.md, docs/tutorials/proposals/update-asset-proposal.md, versioned_docs/version-v0.71/concepts/assets/deposits-withdrawals.md, versioned_docs/version-v0.71/tutorials/proposals/new-asset-proposal.md, versioned_docs/version-v0.71/tutorials/proposals/update-asset-proposal.md
Withdrawal threshold of 0 isn't how it works so it needs an update.
=> Fix withdrawal threshold figure

docs/tutorials/proposals/freeform-proposal.md, docs/tutorials/proposals/network-parameter-proposal.md, docs/tutorials/proposals/new-asset-proposal.md, docs/tutorials/proposals/new-market-proposal.md, docs/tutorials/proposals/update-asset-proposal.md, docs/tutorials/proposals/update-market-proposal.md, versioned_docs/version-v0.71/tutorials/programmatic-trading-basics.md, versioned_docs/version-v0.71/tutorials/proposals/freeform-proposal.md, versioned_docs/version-v0.71/tutorials/proposals/network-parameter-proposal.md, versioned_docs/version-v0.71/tutorials/proposals/new-asset-proposal.md, versioned_docs/version-v0.71/tutorials/proposals/new-market-proposal.md, versioned_docs/version-v0.71/tutorials/proposals/update-asset-proposal.md, versioned_docs/version-v0.71/tutorials/proposals/update-market-proposal.md
=> Add gov site links to proposal tutorials

docs/concepts/vega-chain/data-nodes.md, docs/concepts/vega-chain/network.md, docs/concepts/vega-chain/proof-of-stake.md, docs/concepts/vega-chain/validator-nodes.md, docs/concepts/vega-chain/validator-scores-and-rewards.md, docs/node-operators/get-started/setup-datanode.md, docs/node-operators/requirements/community.md, docs/node-operators/requirements/data-node-infrastructure.md, docs/node-operators/requirements/infrastructure.md, docs/node-operators/requirements/security.md, docs/topics/_topic-data-nodes.mdx, versioned_docs/version-v0.71/concepts/vega-chain/data-nodes.md, versioned_docs/version-v0.71/node-operators/get-started/setup-datanode.md, versioned_docs/version-v0.71/node-operators/requirements/community.md, versioned_docs/version-v0.71/node-operators/requirements/data-node-infrastructure.md, versioned_docs/version-v0.71/node-operators/requirements/infrastructure.md, versioned_docs/version-v0.71/node-operators/requirements/security.md, versioned_docs/version-v0.71/topics/_topic-data-nodes.mdx
=> Enhance infrastructure docs, add perf testing results

docs/concepts/vega-chain/validator-nodes.md, docs/concepts/vega-chain/validator-scores-and-rewards.md, docs/node-operators/get-started/setup-datanode.md, docs/node-operators/get-started/setup-validator.md, versioned_docs/version-v0.71/concepts/vega-chain/validator-nodes.md, versioned_docs/version-v0.71/concepts/vega-chain/validator-scores-and-rewards.md, versioned_docs/version-v0.71/node-operators/get-started/setup-datanode.md, versioned_docs/version-v0.71/node-operators/get-started/setup-validator.md
Correct performance score for candidate validators 
Add more information about event forwarding
Include a data retention note for data node
=> Add validator performance score + data node retention policy changes

docs/releases/overview.md
=> Release notes for 0.72

docs/tools/index.md, docs/tools/vega-wallet/index.md, versioned_docs/version-v0.71/tools/vega-wallet/index.md
Links to the fairground extensions for the Vega Wallet
=> Add wallet extension links to app pages

docs/tools/index.md, docs/tools/vega-protocol-snap.md, versioned_docs/version-v0.72/tools/index.md, versioned_docs/version-v0.72/tools/vega-protocol-snap.md
**DO NOT MERGE AHEAD OF RELEASE DATE**
=> Snaps info

docs/releases/overview.md
updates the release notes page for the latest 0.73.0 preview 6 deployment
=> chore: updates testnet release notes for the 0.73.0preview6 deployment

docs/node-operators/requirements/infrastructure.md, docs/node-operators/requirements/security.md, versioned_docs/version-v0.72/node-operators/requirements/infrastructure.md, versioned_docs/version-v0.72/node-operators/requirements/security.md
=> add gRPC security note + update go version

docs/concepts/trading-on-vega/data-sources.md, docs/tutorials/using-data-sources.md
=> Ethereum oracles concepts

docs/concepts/liquidity/provision.md, docs/releases/overview.md, docs/tutorials/committing-liquidity.md, docs/tutorials/proposals/referral-program-proposal.md, docs/tutorials/proposals/volume-discount-program-proposal.md
=> Create referral & volume discount programs proposals

.gitignore, src/pages/restricted.js, vercel.json
Adds a geo restriction, redirecting some countries to `/restricted` with an explanation. `vercel.json` contains the list of affected countries.
=> geo restrictions

docs/concepts/assets/accounts.md, docs/concepts/assets/transfers.md, docs/concepts/governance.md, docs/concepts/liquidity/rewards-penalties.md, docs/concepts/trading-on-vega/discounts-rewards.md, docs/concepts/trading-on-vega/fees.md, docs/concepts/trading-on-vega/orders.md, docs/concepts/vega-chain/validator-scores-and-rewards.md, docs/releases/overview.md, docs/tutorials/assets-tokens/transferring-assets.md, docs/tutorials/proposals/asset-transfer-proposal.md, docs/tutorials/proposals/freeform-proposal.md, docs/tutorials/proposals/network-parameter-proposal.md, docs/tutorials/proposals/new-asset-proposal.md, docs/tutorials/proposals/new-market-proposal.md, docs/tutorials/proposals/new-perpetuals-market.md, docs/tutorials/proposals/new-successor-market-proposal.md, docs/tutorials/proposals/update-asset-bridge.md, docs/tutorials/proposals/update-asset-proposal.md, docs/tutorials/proposals/update-market-proposal.md, vercel.json, versioned_docs/version-v0.72/concepts/assets/accounts.md, versioned_docs/version-v0.72/concepts/liquidity/rewards-penalties.md, versioned_docs/version-v0.72/concepts/trading-on-vega/discounts-rewards.md, versioned_docs/version-v0.72/concepts/trading-on-vega/fees.md, versioned_docs/version-v0.72/concepts/trading-on-vega/orders.md, versioned_docs/version-v0.72/tutorials/assets-tokens/transferring-assets.md
=> New rewards and discounts page + referrals, activity streaks

versioned_docs/version-v0.73/releases/overview.md
This adds release summary notes for the patch release of 0.73.2
=> chore: add release summary notes for the patch 0.73.2

docs/node-operators/migration-guides/upgrade-node.md, docs/releases/overview.md, versioned_docs/version-v0.73/node-operators/migration-guides/upgrade-node.md
Updates the testnet release summary docs for the 0.73.4 patch release
=> chore: update testnet release summary 0.73.4

docs/releases/overview.md
this adds the release summary notes for v0.73.7
=> chore: add 0.73.7 release summary notes

versioned_docs/version-v0.73/releases/overview.md
Adds release note summary information for the mainnnet release of 0.73.10
=> chore: add release note summary for mainnnet 0.73.10

docs/node-operators/get-started/setup-datanode.md, docs/node-operators/how-to/solve-frequent-issues.md, docs/node-operators/requirements/data-node-infrastructure.md, versioned_docs/version-v0.73/node-operators/get-started/setup-datanode.md, versioned_docs/version-v0.73/node-operators/how-to/solve-frequent-issues.md, versioned_docs/version-v0.73/node-operators/requirements/data-node-infrastructure.md
@peterbarrow found something that had an impact on the data node causing it to deadlock. These changes provide information about that problem and update recommendations for data node.
=> feat: add notes for noatime flag in data node operator guide

docs/tools/index.md, docs/tools/vega-console/_category_.json, docs/tools/vega-console/charts.md, docs/tools/vega-console/host-console-on-ipfs.md, docs/tools/vega-console/index.md, docs/tools/vega-console/vega-console.md
=> Add console section & charts info

docs/tools/index.md, versioned_docs/version-v0.73/tools/index.md, versioned_docs/version-v0.73/tools/vega-console/_category_.json, versioned_docs/version-v0.73/tools/vega-console/charts.md, versioned_docs/version-v0.73/tools/vega-console/host-console-on-ipfs.md, versioned_docs/version-v0.73/tools/vega-console/index.md
=> Add charts page to mainnet side

docs/releases/overview.md
Adds testnet release summary notes to accompany the 0.74.0(preview deployments)
=> chore: add 0.74 testnet release summary notes

docs/releases/overview.md, versioned_docs/version-v0.73/releases/overview.md
Change from BSL to AGPL as core was changed a while back
=> Update  license in overview.md

docs/node-operators/migration-guides/upgrade-node.md, versioned_docs/version-v0.73/node-operators/migration-guides/upgrade-node.md
close https://github.com/vegaprotocol/documentation/issues/910
=> feat: update node operator docs for v0.74

docs/concepts/trading-on-vega/discounts-rewards.md, docs/concepts/trading-on-vega/fees.md, docs/tutorials/assets-tokens/withdrawing-assets.md, docs/tutorials/assets-tokens/withdrawing-vega-tokens.md, versioned_docs/version-v0.74/concepts/trading-on-vega/discounts-rewards.md, versioned_docs/version-v0.74/concepts/trading-on-vega/fees.md
Remove links to the website rewards page.
=> Update reward links

docs/concepts/vega-chain/proof-of-stake.md, docs/releases/overview.md, versioned_docs/version-v0.74/concepts/vega-chain/proof-of-stake.md
Adds testnet release notes for 0.74.5
Also fixes two typos noticed when reviewing staking docs last night
=> feat: add testnet release notes for 0.74.5

docs/releases/overview.md
adds 0.74.6 and 7 testnet release summary notes
=> feat: add 0.74.6 and 7 testnet release summary notes

docs/concepts/assets/transfers.md
Follow up to #972. This page had the incorrect network in frontmatter
=> Fix network for transfers testnet page

docs/concepts/assets/accounts.md, docs/concepts/trading-on-vega/discounts-rewards.md, docs/concepts/trading-on-vega/index.md, docs/concepts/trading-on-vega/margin.md, docs/concepts/trading-on-vega/market-protections.md, docs/tutorials/assets-tokens/transferring-assets.md, docs/tutorials/proposals/asset-transfer-proposal.md
Unhides isolated margin & adds reward cap field to transfers
=> Reveal isolated margin + add reward cap

versioned_docs/version-v0.74/releases/overview.md
Adds release not summary for 0.74.9
=> feat: add release not summary for 0.74.9

docs/releases/overview.md
Adds release summary notes for 0.75-preview-3
=> feat: add release summary notes for 0.75-preview-3

versioned_docs/version-v0.74/releases/overview.md
Adds release note summary for 0.74.10
=> feat: add release note summary for 0.74.10

docs/releases/overview.md
Adds release summary notes for 0.75.0-preview.8
=> feat: add release summary notes for 0.75.0-preview.8

docs/releases/overview.md
Adds release note summary for 0.75.2
=> feat: add release note summary for 0.75.2

docs/releases/overview.md
Adds release summary notes for 0.75.3
=> update feat: add 0.75.3 release summary notes

versioned_docs/version-v0.74/node-operators/get-started/setup-datanode.md
=> feat: Add information for potential crash at block `38535816`

docs/node-operators/migration-guides/upgrade-node.md, docs/releases/overview.md, versioned_docs/version-v0.74/node-operators/migration-guides/upgrade-node.md
=> chore: update 0.75 deployment notes

docs/releases/overview.md
Adds release summary notes for 0.75.7
=> feat: add release summary notes for 0.75.7

docs/node-operators/get-started/setup-datanode.md, versioned_docs/version-v0.75/node-operators/get-started/setup-datanode.md
We must register and have instructions for mainnet operator which wants to run their node from block 0.
=> feat: instruction to recover after failure at block 47865000

docs/api/websocket.md
removed a question mark in the websocket url that shouldn't be there to test my first pull request
=> removed redundant question mark in websocket.md
