vegaprotocol/documentation

docs/tools/vega-wallet/CLI-wallet/create-wallet.md
This PR adds info about deterministic keys to make it clear that when importing an existing wallet and creating credentials, the old keys will also be imported.
=> Add note about deterministic keys

docs/concepts/vega-chain.md
This PR covers the concept of validator scores, in the context of why rewards might not be distributed based on validators not being appropriately staked. 
The info should be correct for version 0.47.5.
=> Add validator score details to concepts

docs/tools/vega-wallet/cli-wallet/latest/create-wallet.md, docs/tools/vega-wallet/desktop-app/index.md, docs/tools/vega-wallet/desktop-app/latest/getting-started.md, docs/tools/vega-wallet/index.md
- Add guidance about Windows Defender. (Even though the software is signed, it still pops up a warning)
- Add info about how to use existing wallet, which is different from restoring wallet
=> Expand desktop wallet guidance

src/components/HomepageFeatures.js
This link was broken, this PR fixes it
=> fixed link on homepage

CONTRIBUTING.md, README.md, VERSIONING.md, package.json
Breaks versioning and local setup out to separate files
This PR adds more details on running Docusaurus locally, which made that section so big that I decided to move it out to a separate file. Then did the same with Versioning. Now the readme is hopefully a little more direct. This replaces #150 which unintentionally included some changes from #111.
=> Make README more approachable

src/css/custom.css
Resolves #71 
Ensures the table of contents submenu code elements have the correct dark text when highlighted and in dark mode.
=> Fix/71: Selected item in page nav invisible (same bg/fg colour)

docs/tools/vega-wallet/cli-wallet/latest/create-wallet.md, versioned_docs/version-v0.53/tools/vega-wallet/cli-wallet/latest/create-wallet.md
As the CLI wallet software is so version-dependent, the pages could use more guidance to help people differentiate. This PR adds caution boxes with links to the other networks' wallet instructions.
=> Highlight which networks the CLI wallets need

docs/api/bridge/index.md, docs/tutorials/staking-tokens.md, package.json, scripts/version-switch.sh, specs/mainnet_contracts.json, specs/testnet_contracts.json, src/components/EthAddresses.js, versioned_docs/version-v0.53/api/bridge/index.md, versioned_docs/version-v0.53/tutorials/staking-tokens.md
Update docs for Sepolia
- Remove @vegaprotocol/smart-contracts-sdk dependency, it is deprecated
- Add json files containing contract addresses
- Remove Ethereum_Network frontmatter in favour of eth network in json
file
- Update EthereumAddresses component to match new labels
Closes #123
=> Switch testnet to sepolia

src/css/custom.css
This reinstates the original styles, by overriding the overrides in the REST theme
- Add styles to custom.css
Closes #318
=> Fix details component styling in non-REST docs

docs/tutorials/transferring-assets.md, versioned_docs/version-v0.53/tutorials/transferring-assets.md
Add `endEpoch` to transfers examples & documentation
The param is optional, but very useful - rather than omit it, this PR adds it to the example code and describes it
in the sections about recurring transfers.
- Add `endEpoch` to recurring transfers tutorial
Closes #330
=> Demonstrate endEpoch in recurring transfers

docusaurus.config.js, package.json, yarn.lock
Search is broken in the current deployment. This fixes it.
It broken when #327 switched us from having /docs as the base path. The search plugin was looking
for that, seeing nothing, and building an empty index. A quick config change fixes it. This PR
also updates the plugin.
- Update @easyops-cn/docusaurus-search-local to 0.33.5
- Fix plugin config to use correct base path
Closes #355
=> Fix broken search

scripts/build-pre-vaguer.sh, specs/mainnet_vaguer_timestamp.json, specs/testnet_vaguer_timestamp.json, src/components/DataNodes.js
Fixes mistmatches between nodes with different subdomains for some APIs.
Also adds a refresh time, so it's clear when the connection star was last checked
- Fix DataNode host matching
- Add refresh time json
- Add refresh time below table
Closes #352
=> Fix DataNodes table matching for some hosts & add refresh time

docusaurus.config.js
Show version switcher in header
Closes #116
=> Enable version switcher

.github/workflows/add_issue_new_projects.yml
The GitHub projects API has been replaced with ProjectsV2. This PR corrects the add issues to project action.
Also removes the external GH action and replaces with a simple mutation for labelling.
=> chore: update add issue to project board

docusaurus.config.js, src/pages/index.js
closes #402 
Before
After
Should improve the preview content that you get when linking to docs from discord twitter etc.
I've made a request for an image [here](https://github.com/vegaprotocol/ux-and-visual-design/issues/85)
=> Fix title and description on homepage

docs/tutorials/using-data-sources.md
Since https://github.com/vegaprotocol/vega/issues/7283 was fixed, it revealed a new problem: the data source spec for Open Oracle format messages in this page was incorrect. It specified signers in a way that was interpreted as a vega key rather than an Ethereum address. It worked in the past, but probably shouldn't have. This PR fixes the specs to be what they should have been all along, and removes the bits that will break with 0.67.0.
I also noticed the graphql shapes were out of date, but rather than fix them I replaced them with links to the REST documentation which is usable in page. This removes a requirement for us to keep them updated.
- Replace in-page graphQL queries with link to the REST page (which let's you execute the query easily)
- Fix Open Oracle data source submission …
=> Fix Using Data Sources tutorial

docs/api/vega-wallet/v2-api/get-started.md
If you're looking to try out the new wallet V2 token before it's released to testnet:
* Use the updated 'getting started' guide, in the [deploy preview](https://deploy-preview-453--vega-docusaurus.netlify.app/testnet/api/vega-wallet/v2-api/get-started).
* Refer to the develop-branch [API documentation playground](https://playground.open-rpc.org/?url=https://raw.githubusercontent.com/vegaprotocol/vega/develop/wallet/api/openrpc.json&uiSchema[appBar][ui:splitView]=false&uiSchema[appBar][ui:input]=false&uiSchema[appBar][ui:examplesDropdown]=false)
**How to try it out**
1. Start the wallet service
On http://localhost:1789/api/v2/requests, send the following body:
```
{
"jsonrpc": "2.0",
"method": "client.connect_wallet",
"id": "make-something-up"
}
```
2. Get the token back from the header …
=> Wallet API v2 updated token guidance

docs/node-operators/get-started/setup-server.md, docs/node-operators/get-started/setup-validator.md, docs/node-operators/how-to/restart-network.md, docs/node-operators/how-to/use-snapshots.md, versioned_docs/version-v0.53/node-operators/migration-guides/upgrade-from-053-to-067.md, versioned_docs/version-v0.53/node-operators/network-restarts.md, versioned_docs/version-v0.53/node-operators/setup-validator.md
Adds the existing upgrading index of links to the mainnet side so it's available on both testnet & mainnet docs for node operators 
Also improves guidance for the home paths to nudge people away from mixing them up
=> Add upgrading index to mainnet

docs/api/vega-wallet/index.md, docs/api/vega-wallet/v2-api/get-started.md, docs/api/vega-wallet/v2-api/index.md, docs/concepts/vega-wallet.md, docs/tools/index.md, docs/tools/vega-wallet/cli-wallet/index.md, docs/tools/vega-wallet/cli-wallet/latest/create-wallet.md, docs/tools/vega-wallet/desktop-app/latest/getting-started.md, docs/tools/vega-wallet/index.md, docs/topics/_topic-wallet.mdx, versioned_docs/version-v0.53/tools/vega-wallet/cli-wallet/latest/create-wallet.md, versioned_docs/version-v0.53/tools/vega-wallet/desktop-app/latest/getting-started.md, versioned_docs/version-v0.53/tools/vega-wallet/index.md
Closes #469 
Closes #471 
Also adds a wallet topic to link across between app guides, concepts & api docs; moves 'command line guidance' down the page on the cli wallet page
=> Wallet docs updates: antivirus note, topic stub 

docs/concepts/new-to-vega.md, docusaurus.config.js, versioned_docs/version-v0.53/concepts/new-to-vega.md
Closes #472 Also removes bounties repo link (not maintained).
=> Add links to mainnet incident reports

src/css/custom.css
Unsatisfyingly: I'm not sure. A theme update perhaps?
=> fix: stubs have double lines in expandy bit

docs/tutorials/proposals/_generated-proposals/_newAsset_annotated.md, docs/tutorials/proposals/_generated-proposals/_newAsset_cmd.md, docs/tutorials/proposals/_generated-proposals/_newAsset_json.md, docs/tutorials/proposals/_generated-proposals/_newAsset_win.md, docs/tutorials/proposals/_generated-proposals/_newFreeform_annotated.md, docs/tutorials/proposals/_generated-proposals/_newFreeform_cmd.md, docs/tutorials/proposals/_generated-proposals/_newFreeform_json.md, docs/tutorials/proposals/_generated-proposals/_newFreeform_win.md, docs/tutorials/proposals/_generated-proposals/_newMarket_annotated.md, docs/tutorials/proposals/_generated-proposals/_newMarket_cmd.md, docs/tutorials/proposals/_generated-proposals/_newMarket_json.md, docs/tutorials/proposals/_generated-proposals/_newMarket_json_instrument.md, docs/tutorials/proposals/_generated-proposals/_newMarket_json_overview.md, docs/tutorials/proposals/_generated-proposals/_newMarket_win.md, docs/tutorials/proposals/_generated-proposals/_updateAsset_annotated.md, docs/tutorials/proposals/_generated-proposals/_updateAsset_cmd.md, docs/tutorials/proposals/_generated-proposals/_updateAsset_json.md, docs/tutorials/proposals/_generated-proposals/_updateAsset_win.md, docs/tutorials/proposals/_generated-proposals/_updateMarket_annotated.md, docs/tutorials/proposals/_generated-proposals/_updateMarket_cmd.md, docs/tutorials/proposals/_generated-proposals/_updateMarket_json.md, docs/tutorials/proposals/_generated-proposals/_updateMarket_win.md, docs/tutorials/proposals/_generated-proposals/_updateNetworkParameter_annotated.md, docs/tutorials/proposals/_generated-proposals/_updateNetworkParameter_cmd.md, docs/tutorials/proposals/_generated-proposals/_updateNetworkParameter_json.md, docs/tutorials/proposals/_generated-proposals/_updateNetworkParameter_win.md, docs/tutorials/using-data-sources.md, scripts/libGenerateProposals/newMarket.js
Fix newMarket proposal
For some reason, this was using the incorrect oracle string. Now it uses the correct one
- Fix new market sample proposal
- Regenerate all sample proposals
Closes #568
=> Fix example new market proposal to have correct oracle

docs/node-operators/how-to/upgrade-network.md
To add some further detail for protocol upgrades to try and mitigate node operators using unsafe-reset-all during a protocol upgrade.
close #577 .
@karlem @daniel1302 - please can you review what has been added here? I have a few questions:
- does this apply to ONLY users not running Visor (i.e. will Visor do all this for them if they are using it)
- should we capture a final step that says "if you see X, Y, Z in the logs the nodes are running as expected" so node operators can validate all went swimmingly
=> chore: update restart docs for protocol upgrade

netlify.toml
Replicates a redirect that was already done for the testnet side.
=> Redirect vega-protocol page to governance page

versioned_docs/version-v0.71/tutorials/proposals/freeform-proposal.md, versioned_docs/version-v0.71/tutorials/proposals/network-parameter-proposal.md
We missed some incorrect uses of the testnet governance site in the mainnet section. This PR fixes both.
=> Fix incorrect governance links

docs/tutorials/proposals/_generated-proposals/_newAsset_annotated.md, docs/tutorials/proposals/_generated-proposals/_newAsset_cmd.md, docs/tutorials/proposals/_generated-proposals/_newAsset_json.md, docs/tutorials/proposals/_generated-proposals/_newAsset_win.md, docs/tutorials/proposals/_generated-proposals/_newFreeform_annotated.md, docs/tutorials/proposals/_generated-proposals/_newFreeform_cmd.md, docs/tutorials/proposals/_generated-proposals/_newFreeform_json.md, docs/tutorials/proposals/_generated-proposals/_newFreeform_win.md, docs/tutorials/proposals/_generated-proposals/_newMarket_annotated.md, docs/tutorials/proposals/_generated-proposals/_newMarket_cmd.md, docs/tutorials/proposals/_generated-proposals/_newMarket_json.md, docs/tutorials/proposals/_generated-proposals/_newMarket_json_overview.md, docs/tutorials/proposals/_generated-proposals/_newMarket_win.md, docs/tutorials/proposals/_generated-proposals/_updateAsset_annotated.md, docs/tutorials/proposals/_generated-proposals/_updateAsset_cmd.md, docs/tutorials/proposals/_generated-proposals/_updateAsset_json.md, docs/tutorials/proposals/_generated-proposals/_updateAsset_win.md, docs/tutorials/proposals/_generated-proposals/_updateMarket_annotated.md, docs/tutorials/proposals/_generated-proposals/_updateMarket_cmd.md, docs/tutorials/proposals/_generated-proposals/_updateMarket_json.md, docs/tutorials/proposals/_generated-proposals/_updateMarket_win.md, docs/tutorials/proposals/_generated-proposals/_updateNetworkParameter_annotated.md, docs/tutorials/proposals/_generated-proposals/_updateNetworkParameter_cmd.md, docs/tutorials/proposals/_generated-proposals/_updateNetworkParameter_json.md, docs/tutorials/proposals/_generated-proposals/_updateNetworkParameter_win.md, scripts/generate_proposals.js, scripts/libGenerateProposals/newMarket.js
In the generated examples of proposals, the example code given was passing in timestamps as number of milliseconds since the epoch, rather than number of seconds which is what is actually required.
=> fix: example timestamps should be in seconds, not milliseconds, since epoch

docs/node-operators/get-started/setup-datanode.md, versioned_docs/version-v0.71/node-operators/get-started/setup-datanode.md
The motivation for this change is that validators are using commands directly from docs, and the command needed to be corrected. 
The issue is that the PostgreSQL container has a volume that needs to be added. It causes the entire data for the PostgreSQL to be lost when the container is stopped or crashed. This is what happened to the validator yesterday.
=> feat: fix postgresql command and add example

specs/mainnet_contracts.json, versioned_docs/version-v0.71/releases/overview.md
This PR adds release summary notes for the 0.71.5 patch release leveraging the [content within the incident blog](https://medium.com/vegaprotocol/incident-report-incident-under-investigation-d41cb2815de0) due to the sensitivity of the bug the patch resolves.
=> feat: add release summary notes for mainnet 0.71.5

vercel.json
Change vercel configuration to match the old Netlify setup. This prevents a brief flash of 404.
=> chore: fix 404 on load

docs/releases/overview.md, versioned_docs/version-v0.71/releases/overview.md
This PR updates 0.70.0 release notes based on feedback of a breaking change not being clear in the changelog and associated release summary notes (inc stripping some trailing spaces).
It also adds more detail and links to the 0.71.5 patch release summary notes.
=> fix: make 0.70.0 and 0.71.5 details more clear

docs/releases/overview.md
Adds release summary notes for 0.71.6 for the fairground deployment.
When this deployment goes to the validators I will update with a link to the release page in both the versioned docs and here.
=> chore: update releaase summary for 0.71.6 on fairground

docs/releases/overview.md, versioned_docs/version-v0.73/releases/overview.md
add mainnet release summary notes for 0.73.6
also fixes a date typo in the testnet summary
=> chore: add mainnet release summary notes for 0.73.6

docs/tutorials/proposals/_generated-proposals/_newSuccessorMarket_annotated.md, docs/tutorials/proposals/_generated-proposals/_newSuccessorMarket_cmd.md, docs/tutorials/proposals/_generated-proposals/_newSuccessorMarket_json.md, docs/tutorials/proposals/_generated-proposals/_newSuccessorMarket_win.md, scripts/build.sh, scripts/libGenerateProposals/newMarket.js, scripts/libGenerateProposals/newSuccessorMarket.js, versioned_docs/version-v0.73/tutorials/proposals/_generated-proposals/_newSuccessorMarket_annotated.md, versioned_docs/version-v0.73/tutorials/proposals/_generated-proposals/_newSuccessorMarket_cmd.md, versioned_docs/version-v0.73/tutorials/proposals/_generated-proposals/_newSuccessorMarket_json.md, versioned_docs/version-v0.73/tutorials/proposals/_generated-proposals/_newSuccessorMarket_win.md
Fix #853
- Remove automatic proposal generation on build
- Add missing fields back to successor template
- Regenerate successor market proposals
=> fix successor market examples

docs/node-operators/get-started/setup-datanode.md, docs/node-operators/how-to/solve-frequent-issues.md, versioned_docs/version-v0.73/node-operators/get-started/setup-datanode.md, versioned_docs/version-v0.73/node-operators/how-to/solve-frequent-issues.md
1. Mark the `max_locks_per_transaction` parameter as required to change in the PostgreSQL prepare docs
2. Add frequent issues related to the above parameter.
3. Add info about patches required for the consensus failure at block 26439343
=> feat: Update operator docs

docs/releases/overview.md
Adds release note content for 0.73.10 patch released to testnet on the 21st December 2023.
=> chore: update testnet 0.73.10 patch release notes

docs/releases/overview.md, versioned_docs/version-v0.73/releases/overview.md
Adds release summary notes for the 0.73.11 and .12 patch releases.
Mainnet DATES TBC....
=> chore: add 0.73.11 and 0.73.12 (combined) release summary notes (testnet and mainnet)

docs/concepts/trading-on-vega/margin.md, src/components/NetworkParameter.js
After upgrading docusaurus, the way the NetworkParameter component was waiting for data to be fetch is no longer valid.
This PR adds a small fudge to keep the old behaviour with basically the same code
=> Fix client side navigation error

versioned_docs/version-v0.73/releases/overview.md
This adds release summary notes for the up coming patch fix related to the mainnet incident when terminating the LINK/USDT market
=> chore: add release summary notes for the 73.13 patch fix

versioned_docs/version-v0.73/releases/overview.md
As the patch version that went out for the network outage didnt up the semver version this PR combines the releases into one entry for that day
=> chore: update release summary version numbers

docs/releases/overview.md
This PR updates the 0.74 release summary notes to be in line with what will be published for mainnet
=> chore: update 0.74 testnet release notes

versioned_docs/version-v0.73/releases/overview.md
Updates the release summary notes as per the incident:
- https://blog.vega.xyz/incident-report-bridge-stopped-by-validators-9e3feb7bea78
=> feat: add 0.73.14 release notes

.gitignore, .yarnclean, babel.config.js, docusaurus.config.js, package.json, src/plugins/webpack-docusaurus-plugin.config.js, yarn.lock
- **ci: experiment with options**
It's not entirely clear what is making Vercel sigkill/ooo. This branch has landed on disabling Webpack's build cache (written to `.node_modules/cache`), rather than disabling ALL build caching. This means that `node_modules` should persist across builds (for a minor speedup). Also cleaning up unneccessary junk to speed up that caching
- Add `src/plugins/webpack-docusaurus-plugin.config.js` to:
- Disable webpack cache in CI only
- Disable webpackbar for more verbose log output
- Force clear `node_modules/.cache` in CI only
- Bump `swc-core` 
- Use ESBuild for terser minification
=> build-speed-experiments

versioned_docs/version-v0.74/releases/overview.md
Adds release summary notes for the restoration of the manipulated balance in the following  [mainnet incident ↗](https://medium.com/vegaprotocol/incident-report-network-outage-e60376912790) report.
=> add release note for 0.74.4

versioned_docs/version-v0.74/releases/overview.md
adds mainnet release notes for 0.74.5, 0.74.6 and 0.74.7
@candida-d I have excluded the ELS API change but would appreciate you  looking to see if we should include?
=> feat: add mainnet release notes for 0.74.5 to 0.74.7

docs/node-operators/get-started/setup-validator.md, docs/node-operators/migration-guides/upgrade-node.md, versioned_docs/version-v0.75/node-operators/migration-guides/upgrade-node.md
Some of the RPC endpoints return  the following error when values for `fromBlock` and `toBlock` are not prefixed with 0x:
```
{"jsonrpc":"2.0","id":1,"error":{"code":-32602,"message":"invalid argument 0: hex string without 0x prefix"}}
```
=> feat: update from and to blocks range in the arbitrum rpc query to hex ones

docs/api/architecture.md, docs/api/bridge/index.md, docs/api/overview.md, docs/tutorials/assets-tokens/staking-tokens.md, specs/mainnet_contracts.json, specs/testnet_contracts.json, src/components/EthAddresses.js, versioned_docs/version-v0.76/api/bridge/index.md, versioned_docs/version-v0.76/tutorials/assets-tokens/staking-tokens.md
- Suggestion: 'Bridges & Contracts'
=> Update contract addresses component to improve multichain clarity
